"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {Bookmark,Flag,Eraser} from "lucide-react";
import {examPassages,allQuestions} from "../../data/passages";

function fmt(t){const h=Math.floor(t/3600),m=Math.floor((t%3600)/60),s=t%60;return `${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`}
function buildStats(answers){const stats={};allQuestions.forEach(q=>{if(!stats[q.type])stats[q.type]={correct:0,total:0};stats[q.type].total++;if(answers[q.id]===q.answer)stats[q.type].correct++});return stats}

export default function Exam(){
 const ref=useRef(null),[current,setCurrent]=useState(0),[answers,setAnswers]=useState({}),[struck,setStruck]=useState({}),[flagged,setFlagged]=useState({}),[mode,setMode]=useState("exam"),[seconds,setSeconds]=useState(0),[running,setRunning]=useState(true);
 const q=allQuestions[current],passage=examPassages.find(p=>p.id===q.passageId),score=useMemo(()=>allQuestions.reduce((sum,x)=>sum+(answers[x.id]===x.answer?1:0),0),[answers]),stats=useMemo(()=>buildStats(answers),[answers]);
 useEffect(()=>{if(!running||mode!=="exam")return;const id=setInterval(()=>setSeconds(x=>x+1),1000);return()=>clearInterval(id)},[running,mode]);
 function highlight(){const sel=window.getSelection();if(!sel||!sel.rangeCount||!sel.toString().trim())return;if(!ref.current?.contains(sel.anchorNode))return;const range=sel.getRangeAt(0),span=document.createElement("span");span.className="highlighted";try{range.surroundContents(span);sel.removeAllRanges()}catch{alert("Try highlighting a smaller section.")}}
 function clearH(){ref.current?.querySelectorAll(".highlighted").forEach(s=>s.replaceWith(document.createTextNode(s.textContent)))}
 function strike(l,e){e.stopPropagation();const key=`${q.id}-${l}`;setStruck({...struck,[key]:!struck[key]})}
 if(mode==="review"){const unanswered=allQuestions.filter(x=>!answers[x.id]).length,flaggedCount=Object.values(flagged).filter(Boolean).length;return <div className="reviewWrap"><header className="reviewHeader"><h1>Review Your Section</h1><p>Check unanswered or flagged questions before submitting.</p></header><main className="reviewMain"><section className="reviewGrid"><div className="reviewCard"><h2>{Object.keys(answers).length}/{allQuestions.length}</h2><p>Answered</p></div><div className="reviewCard"><h2>{unanswered}</h2><p>Unanswered</p></div><div className="reviewCard"><h2>{flaggedCount}</h2><p>Flagged</p></div></section><section className="reviewCard"><h2>Question Review</h2>{allQuestions.map((item,idx)=><div className="reviewQuestion" key={item.id}><div><strong>Question {item.id}</strong> — {item.type}<br/><small>{item.passageTitle}</small></div><div>{answers[item.id]?<span className="pill good">Answered</span>:<span className="pill bad">Unanswered</span>} {flagged[item.id]&&<span className="pill flag">Flagged</span>} <button className="secondary" onClick={()=>{setCurrent(idx);setMode("exam");setRunning(true)}}>Go To</button></div></div>)}</section><div className="actions"><button className="secondary" onClick={()=>{setMode("exam");setRunning(true)}}>Return to Exam</button><button className="primary" onClick={()=>{setRunning(false);setMode("results")}}>Submit Section</button></div></main></div>}
 if(mode==="results"){return <div className="reviewWrap"><header className="reviewHeader"><h1>Section Results</h1><p>Score: {score}/{allQuestions.length} • Time elapsed: {fmt(seconds)}</p></header><main className="reviewMain"><section className="reviewGrid"><div className="reviewCard"><h2>{Math.round(score/allQuestions.length*100)}%</h2><p>Accuracy</p></div><div className="reviewCard"><h2>{score}</h2><p>Correct</p></div><div className="reviewCard"><h2>{allQuestions.length-score}</h2><p>Missed</p></div></section><section className="reviewCard"><h2>Accuracy by Question Type</h2><table className="statsTable"><thead><tr><th>Type</th><th>Correct</th><th>Total</th><th>Accuracy</th></tr></thead><tbody>{Object.entries(stats).map(([type,s])=><tr key={type}><td>{type}</td><td>{s.correct}</td><td>{s.total}</td><td>{Math.round(s.correct/s.total*100)}%</td></tr>)}</tbody></table></section><section className="reviewCard"><h2>Detailed Review</h2>{allQuestions.map((item,idx)=><div className="reviewQuestion" key={item.id}><div><strong>Question {item.id}</strong> — Your answer: {answers[item.id]||"Blank"} | Correct: {item.answer}<br/><small>{item.explanation}</small></div><button className="secondary" onClick={()=>{setCurrent(idx);setMode("exam")}}>Review</button></div>)}</section></main></div>}
 return <div className="exam"><header className="examTop"><div><b>Medical College Admission Test</b> — CARS Mastery V2</div><div>Time Elapsed: <b>{fmt(seconds)}</b> <button className="navBtn" onClick={()=>setRunning(!running)}>{running?"Pause":"Resume"}</button></div></header><div className="examTools"><div><button className="toolBtn" onClick={highlight}><span className="yellow"/>Highlight</button><button className="toolBtn">Strikethrough answers with “S”</button><button className="toolBtn" onClick={clearH}><Eraser size={15}/> Clear</button></div><button className="toolBtn" onClick={()=>setFlagged({...flagged,[q.id]:!flagged[q.id]})}><Flag size={15}/> Flag for Review</button></div><main className="mainExam"><section className="passage" ref={ref}><h2>{passage.title}</h2><div className="passageMeta">{passage.category} • Question {q.id} of {allQuestions.length}</div>{passage.paragraphs.map((p,i)=><p key={i}>{p}</p>)}</section><section className="question"><div className="qHeader"><div><div className="questionType">{q.type}</div><h2>Question {q.id}</h2></div><button className="toolBtn" onClick={()=>setFlagged({...flagged,[q.id]:!flagged[q.id]})}><Bookmark color={flagged[q.id]?"#dc2626":"#0868a8"}/></button></div><p>{q.stem}</p>{Object.entries(q.choices).map(([l,text])=>{const selected=answers[q.id]===l,key=`${q.id}-${l}`;let cls="choice";if(selected)cls+=" selected";if(struck[key])cls+=" struck";return <button key={l} className={cls} onClick={()=>setAnswers({...answers,[q.id]:l})}><span className="bubble"/><span><b>{l}.</b> <span className="choiceText">{text}</span><span onClick={(e)=>strike(l,e)} style={{marginLeft:12,color:"#075fa8",fontWeight:700}}>S</span></span></button>})}</section><aside className="qnavPanel"><h3>Questions</h3><div className="navGrid">{allQuestions.map((x,i)=>{let cls="qBox";if(i===current)cls+=" current";else if(answers[x.id])cls+=" answered";if(flagged[x.id])cls+=" flagged";return <button key={x.id} className={cls} onClick={()=>setCurrent(i)}>{x.id}</button>})}</div><p><small>Blue = current<br/>Green = answered<br/>Yellow outline = flagged</small></p></aside></main><footer className="examBottom"><button className="endBtn" onClick={()=>{setRunning(false);setMode("review")}}>End Section</button><div>{Object.keys(answers).length} of {allQuestions.length} answered</div><div><button className="navBtn" onClick={()=>setCurrent(Math.max(0,current-1))}>← Previous</button> <button className="navBtn" onClick={()=>setCurrent(Math.min(allQuestions.length-1,current+1))}>Next →</button></div></footer></div>
}
